"""Constants for dashcam-downloader."""

APP_NAME = "dashcam-downloader"
APP_VERSION = "1.0.0"

DEFAULT_DASHCAM_BASE_URL = "http://192.168.68.17"
DEFAULT_DASHCAM_INDEX_PATH = "/blackvue_vod.cgi"
DEFAULT_DOWNLOAD_DIR = "/downloads"
DEFAULT_POLL_INTERVAL_SECONDS = 60
DEFAULT_COMPLETE_FILE_SIZE = 1_000_000
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
DEFAULT_DOWNLOAD_RETRIES = 3
DEFAULT_RETRY_DELAY_SECONDS = 10
DEFAULT_QUEUE_MAX_SIZE = 1000

RECORD_PATH_PREFIX = "/Record/"
TEMP_FILE_SUFFIX = ".part"
DOWNLOAD_CHUNK_SIZE = 1024 * 1024

